version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: carford_user
      POSTGRES_PASSWORD: carford_password
      POSTGRES_DB: carford_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      FLASK_DEBUG: 'true'
      DATABASE_URL: postgres://carford_user:carford_password@db:5432/carford_db

  frontend:
    build: ./frontend
    command: python3 -m http.server 8000
    volumes:
      - ./frontend:/frontend
    ports:
      - '8000:8000'

volumes:
  postgres_data:
